CREATE DATABASE IF NOT EXISTS voituredb;

USE voituredb;

CREATE TABLE IF NOT EXISTS cars (
    id VARCHAR(255) PRIMARY KEY,
    model VARCHAR(255) NOT NULL,
    owner VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS clients (
    id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
